home:
    path: /
    controller: App\Controller\HomeController::home

homePage:
    path: /home
    controller: App\Controller\HomeController::home

saveRates:
    path: /fetch-rates
    controller: App\Controller\ExchangeRateController::fetchRates
    
getData:
    path: /get-data
    controller: App\Controller\HomeController::getData

